import { SITE_URL } from '@config/constants';
/** Client helper exposing SEO endpoint URLs generated by Firebase Functions. */
export const useSitemap = () => ({ sitemapUrl: `${SITE_URL}/sitemap.xml`, rssUrl: `${SITE_URL}/rss.xml` });
